services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./certs:/app/certs

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    ports:
      - '8001:8000'
    volumes:
      - ./certs:/opt/keycloak/certs
      - ./keycloak_data:/opt/keycloak/data
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command: start

